import ControlsPanel from "./components/ControlsPanel";
import LayerToggles from "./components/LayerToggles";
import Legend from "./components/Legend";
import MapCanvas from "./components/MapCanvas";
import SidePanel from "./components/SidePanel";
import TimelinePanel from "./components/TimelinePanel";
import { useKeyboardControls } from "./hooks/useKeyboardControls";
import { usePlayback } from "./hooks/usePlayback";
import { useReplay } from "./hooks/useReplay";

export default function App() {
  const { replay, error } = useReplay();
  const playback = usePlayback(replay);

  useKeyboardControls({
    togglePlay: () => playback.setPlaying(!playback.playing),
    previousStep: playback.previousStep,
    nextStep: playback.nextStep,
    previousSearchFrame: playback.previousSearchFrame,
    nextSearchFrame: playback.nextSearchFrame,
    switchAgent: playback.switchAgent,
    toggleLayer: playback.toggleLayer
  });

  if (error) {
    return (
      <main className="flex min-h-screen items-center justify-center bg-arena-bg p-6">
        <div className="max-w-xl rounded-lg border border-red-400/40 bg-red-950/30 p-6">
          <h1 className="text-xl font-semibold text-red-100">Replay load failed</h1>
          <p className="mt-2 text-red-200">{error}</p>
          <p className="mt-4 text-sm text-red-100">Run python scripts/generate_replay.py to create visualizer/public/sample_replay.json.</p>
        </div>
      </main>
    );
  }

  if (!replay || !playback.step || !playback.trace) {
    return (
      <main className="flex min-h-screen items-center justify-center bg-arena-bg">
        <div className="rounded-lg border border-arena-line bg-arena-panel px-6 py-4 text-arena-muted">Loading replay...</div>
      </main>
    );
  }

  return (
    <main className="min-h-screen bg-arena-bg p-4 text-arena-text">
      <div className="mx-auto flex max-w-[1680px] flex-col gap-4">
        <header className="rounded-lg border border-arena-line bg-gradient-to-r from-arena-panel to-slate-900 p-5">
          <p className="text-xs uppercase tracking-[0.22em] text-cyan-300">Introduction to Artificial Intelligence - Lab 1</p>
          <h1 className="mt-2 text-3xl font-semibold text-white">Hide and Seek Arena Search Debugger</h1>
          <p className="mt-2 max-w-4xl text-sm leading-6 text-arena-muted">
            Educational replay viewer for BFS, A*, flood fill, minimax, alpha-beta pruning, and heuristic evaluation.
            The frontend reads static JSON generated by the Python simulator and does not call Python from the browser.
          </p>
        </header>

        <section className="grid gap-4 xl:grid-cols-[minmax(680px,1fr)_420px]">
          <div className="flex flex-col gap-4">
            <MapCanvas
              grid={replay.map}
              width={replay.width}
              height={replay.height}
              step={playback.step}
              trace={playback.trace}
              activeAgent={playback.activeAgent}
              searchFrame={playback.searchFrame}
              layers={playback.layers}
            />
            <ControlsPanel
              playing={playback.playing}
              setPlaying={playback.setPlaying}
              speed={playback.speed}
              setSpeed={playback.setSpeed}
              activeAgent={playback.activeAgent}
              setActiveAgent={playback.setActiveAgent}
              previousStep={playback.previousStep}
              nextStep={playback.nextStep}
              previousSearchFrame={playback.previousSearchFrame}
              nextSearchFrame={playback.nextSearchFrame}
            />
            <TimelinePanel
              stepIndex={playback.stepIndex}
              totalSteps={playback.totalSteps}
              setStepIndex={playback.setStepIndex}
              searchFrame={playback.searchFrame}
              maxFrames={playback.maxFrames}
              setSearchFrame={playback.setSearchFrame}
            />
          </div>

          <div className="flex flex-col gap-4">
            <SidePanel
              step={playback.step}
              trace={playback.trace}
              activeAgent={playback.activeAgent}
              searchFrame={playback.searchFrame}
              maxFrames={playback.maxFrames}
            />
            <LayerToggles layers={playback.layers} toggleLayer={playback.toggleLayer} />
            <Legend />
          </div>
        </section>
      </div>
    </main>
  );
}
